services:
  postgres:
    image: postgres:15
    container_name: balance-postgres
    environment:
      POSTGRES_DB: balance_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

